// <auto-generated />
using System;
using ConferenceLeadGen.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConferenceLeadGen.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828175348_AddZohoAccountIdToDistrictsAndSchools")]
    partial class AddZohoAccountIdToDistrictsAndSchools
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConferenceLeadGen.Api.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CandidateMatches")
                        .HasColumnType("jsonb")
                        .HasColumnName("candidate_matches");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("ExtractionConfidence")
                        .HasColumnType("text")
                        .HasColumnName("extraction_confidence");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LocalDuplicateOfContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_duplicate_of_contact_id");

                    b.Property<string>("MatchConfidence")
                        .HasColumnType("text")
                        .HasColumnName("match_confidence");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_status");

                    b.Property<string>("MatchedZohoAccountId")
                        .HasColumnType("text")
                        .HasColumnName("matched_zoho_account_id");

                    b.Property<string>("MatchedZohoContactId")
                        .HasColumnType("text")
                        .HasColumnName("matched_zoho_contact_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_status");

                    b.Property<Guid>("SchoolDistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_district_id");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceImageHash")
                        .HasColumnType("text")
                        .HasColumnName("source_image_hash");

                    b.Property<string>("SourceImagePath")
                        .HasColumnType("text")
                        .HasColumnName("source_image_path");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_contacts_event_id");

                    b.HasIndex("LocalDuplicateOfContactId")
                        .HasDatabaseName("ix_contacts_local_duplicate_of_contact_id");

                    b.HasIndex("SchoolDistrictId")
                        .HasDatabaseName("ix_contacts_school_district_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_contacts_school_id");

                    b.HasIndex("SourceImageHash")
                        .IsUnique()
                        .HasDatabaseName("ix_contacts_source_image_hash")
                        .HasFilter("source_image_hash IS NOT NULL");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("ConferenceLeadGen.Api.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("ZohoCampaignId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zoho_campaign_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("ConferenceLeadGen.Api.Models.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ZohoAccountId")
                        .HasColumnType("text")
                        .HasColumnName("zoho_account_id");

                    b.HasKey("Id")
                        .HasName("pk_schools");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("ix_schools_district_id");

                    b.HasIndex("ZohoAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_schools_zoho_account_id")
                        .HasFilter("zoho_account_id IS NOT NULL");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("ConferenceLeadGen.Api.Models.SchoolDistrict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("ZohoAccountId")
                        .HasColumnType("text")
                        .HasColumnName("zoho_account_id");

                    b.HasKey("Id")
                        .HasName("pk_school_districts");

                    b.HasIndex("ZohoAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_school_districts_zoho_account_id")
                        .HasFilter("zoho_account_id IS NOT NULL");

                    b.ToTable("school_districts", (string)null);
                });

            modelBuilder.Entity("ConferenceLeadGen.Api.Models.Contact", b =>
                {
                    b.HasOne("ConferenceLeadGen.Api.Models.Event", "Event")
                        .WithMany("Contacts")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contacts_events_event_id");

                    b.HasOne("ConferenceLeadGen.Api.Models.Contact", null)
                        .WithMany()
                        .HasForeignKey("LocalDuplicateOfContactId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contacts_contacts_local_duplicate_of_contact_id");

                    b.HasOne("ConferenceLeadGen.Api.Models.SchoolDistrict", "SchoolDistrict")
                        .WithMany()
                        .HasForeignKey("SchoolDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contacts_school_districts_school_district_id");

                    b.HasOne("ConferenceLeadGen.Api.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contacts_schools_school_id");

                    b.Navigation("Event");

                    b.Navigation("School");

                    b.Navigation("SchoolDistrict");
                });

            modelBuilder.Entity("ConferenceLeadGen.Api.Models.School", b =>
                {
                    b.HasOne("ConferenceLeadGen.Api.Models.SchoolDistrict", "District")
                        .WithMany("Schools")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schools_school_districts_district_id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("ConferenceLeadGen.Api.Models.Event", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("ConferenceLeadGen.Api.Models.SchoolDistrict", b =>
                {
                    b.Navigation("Schools");
                });
#pragma warning restore 612, 618
        }
    }
}
